### ISSUE TITLE
Any support for Python39

### ISSUE THREAD

**Issue by mediabuff** [henon/Python.Included#51] opened 2023-05-14 22:05 UTC

**Comment by henon** [comment] 2023-05-15 07:37
what you mean?

**Comment by henon** [comment] 2023-05-16 05:50
Duplicate of #48

I want to keep the package simple by only bundling the latest version. But you can use the `Python.Deployment` nuget to easily install any python version you like from various sources, either by downloading it on-the-fly from the internet or by bundling it yourself as an assembly resource. Check out the examples in this repo.

**Closed by henon** 2023-05-16 05:50 UTC
