### ISSUE TITLE
How can I use Python third-party libraries

### ISSUE THREAD

**Issue by wf-soft** [henon/Python.Included#11] opened 2020-07-26 16:30 UTC
Can you add examples of Python using third-party libraries

**Comment by henon** [comment] 2020-07-27 17:06
We have to port the improvements epignatelli made in his fork at https://github.com/epignatelli/Python.Included back to this repo in order to use `pip3` for installing any library. 

I wanted do it eventually but hadn't found time yet. If you feel up to it, could you do it and send a PR?

**Comment by henon** [comment] 2020-07-28 06:44
Also, if you are interested in embedding *.whl files, here is the code from Numpy.NET that installs the numpy wheel which is attached to the assembly as an embedded resource:

```c#
        private static PyObject InstallAndImport(bool force = false)
        {
            Installer.SetupPython(force).Wait();
            Installer.InstallWheel(typeof(np).Assembly, "numpy-1.16.3-cp37-cp37m-win_amd64.whl").Wait();
            PythonEngine.Initialize();
            var mod = Py.Import("numpy");
            return mod;
        }
```

**Comment by henon** [comment] 2020-07-30 07:26
What do you say, does it solve your issue?

**Comment by Nannoussa** [comment] 2020-07-30 12:30
Hello @henon , I can import the improvements that epignatelli had made, if you want.
Just tell me if there is any guidelines to do it properly and I'll make a PR for you. 
What do you think?

**Comment by henon** [comment] 2020-07-30 13:11
Awesome Nannoussa, thank you!

I guess the installation routine should be tested to prove that it can install one of the more complicated Python libaries such as Tensorflow (or whatever lib you deem appropriate for a test case). Please add an example project like the one that already exists so others can reproduce the test.

Epignatelli marked an installation method that is used by Numpy.NET with the  [Obsolete] attribute. That obviously shouldn't be backportet.

**Comment by Nannoussa** [comment] 2020-07-30 13:33
You're welcome!!
We all seek the same thing, to make things work and to keep improving what we do. I'll use TensorFlow and spacy as testing packages.
But I have one question about the   " Installer.InstallPip();" even on your console app it didn't work, should I assume that it didn't work from the beginning or because it calls an older python version?  
Thanks

**Comment by henon** [comment] 2020-07-30 13:42
Epignatelli added and PR'ed InstallPip() but I didn't verify it at the time. Then he improved it but didn't PR any more. I guess because he had deviated from my fork too much.

**Comment by Nannoussa** [comment] 2020-08-03 07:55
Hello @henon, after investigation and testing, I think there is a problem we need to talk about. I don't know if I need to share it here or join you in private. Let me know :)
Thanks.

**Comment by henon** [comment] 2020-08-03 07:58
we can discuss it here, I am sure

**Comment by Nannoussa** [comment] 2020-08-03 08:11
Okay, You are using Python.Runtime.NetStandard (3.7.0) in your original code with .net framework 2.0 but the package is deprecated and no longer supported or maintained, so we need to use pythonnet instead, however, pythhonnet is base on .net framework 4.6 and bigger. 
Changing the whole project .Net framework version is up to you. 
So you need to tell me what do you want so I can continue the work.
PS: Pip is working but couldn't go further with the testing cause I encountered this issue in the fork cause obviously Epignatelli tried to get rid of the deprecated package too.

**Comment by henon** [comment] 2020-08-03 08:15
I have been busy myself over the weekend. I deprecated the package myself and replaced it with a newer compiled for .net standard. It is now named pythonnet_netstandard_py37_win.nuget 

Please just sync with my repo (rebase your changes onto mine) and everything will be OK again.

**Comment by Nannoussa** [comment] 2020-08-03 08:17
Perfect okay I 'll rebase the changes and test directly in your project. :) Thanks

**Comment by wf-soft** [comment] 2020-08-03 08:24
What, pythonnet_netstandard_py37_win better than this？

**Comment by Nannoussa** [comment] 2020-08-03 08:28
@wf-soft  Python.Included is based on pythonnet already but with the ability to install and use python interp with any environment without setting it up manually.

**Comment by wf-soft** [comment] 2020-08-03 08:31
Yes, Python.Included It's easy to use

**Comment by henon** [comment] 2020-08-03 08:32
the Python.Runtime.NetStandard  package was based on pythonnet v130 if I remember correctly. The package name caused some confusion. Since the pythonnet team doesn't release nugets for all configurations I did that for them and changed the package name to pythonnet (for net40 platform) and pythonnet_netstandard (for netstandard2.0). 

Since then pythonnet released new versions, they are now at v151. I pulled up my fork of pythonnet, which is actually 1:1 the same just with a release bot to compile it for all platforms, all python versions and .net frameworks.

**Comment by henon** [comment] 2020-08-03 08:47
@Nannoussa sorry I had forgotten to push my changes to this repo. now they are online

**Comment by Nannoussa** [comment] 2020-08-03 09:27
@henon, I created a PR and resolved conflicts, could you please review it? Thanks

**Comment by henon** [comment] 2020-08-03 10:36
thank you for adding the test project. directly merging epignatelli's changes is not what I want though, so i'll cherry pick the good commits, leave out the .netFramework conversion and the BHOM package changes, then merge your test project and then you can check if it still works as expected. 

Is .Net Standard 2.0 ok for you?

**Comment by henon** [comment] 2020-08-03 11:09
Just merged and tried. For me it doesn't work. When I execute the command in cmd.exe I get this error

```
C:\Users\henon>C:\Users\henon\AppData\Local\python-3.7.3-embed-amd64\Scripts\pip3 install spacy
Traceback (most recent call last):
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\henon\AppData\Local\python-3.7.3-embed-amd64\Scripts\pip3.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

C:\Users\henon>
```

**Comment by henon** [comment] 2020-08-03 11:37
It is working now, I had to remove my old installation which had a buggy version of pip. Also your test project didn't ouput the spacy version correctly. Now it does, check my latest push.

**Comment by henon** [comment] 2020-08-03 11:37
The changes have been released to nuget: https://www.nuget.org/packages/Python.Included/latest

**Comment by Nannoussa** [comment] 2020-08-03 11:42
@henon , Sorry for the inconvenience, I was outside, I just saw your messages. 
Glad it works. Thank you so much for the release.

**Comment by Nannoussa** [comment] 2020-08-04 09:30
@henon , I have a suggestion about InstalPython task, how about adding Install_Path as input parameter which takes per default the path specified if no path was given? cause sometimes the servers we want to deploy our apps to are restrictive( no full permissions to install, copy or delete) but there is always shared folders as a workaround.
What do u think?

**Comment by henon** [comment] 2020-08-04 11:44
of course, good idea. this is so small, I'll add it right away.

**Comment by henon** [comment] 2020-08-04 11:48
actually, I just discovered that Installer.INSTALL_PATH can be set to any path you like.  I guess you only need the variable Installer.EMBEDDED_PYTHON to be overridable too so you can also customize the folder name

**Comment by henon** [comment] 2020-08-04 11:53
Now it is fully customizable:

```c#
        /// <summary>
        /// Path to install python. If needed, set before calling SetupPython().
        /// <para>Default is: Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)</para>
        /// </summary>
        public static string InstallPath { get; set; } = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

        /// <summary>
        /// Name of the python directory. If needed, set before calling SetupPython().
        /// Defaults to python-3.7.3-embed-amd64
        /// </summary>
        public static string InstallDirectory { get; set; } = "python-3.7.3-embed-amd64";

        /// <summary>
        /// The full path to the Python directory. Customize this by setting InstallPath and InstallDirectory
        /// </summary>
        public static string EmbeddedPythonHome => Path.Combine(InstallPath, InstallDirectory);
```

**Comment by Nannoussa** [comment] 2020-08-04 13:50
That's even better :D Thanks a lot my friend <3

**Comment by Nannoussa** [comment] 2020-08-04 13:53
@henon , Do you need to make a new release for those changes?

**Comment by henon** [comment] 2020-08-04 13:58
I released the change to nuget, will be available shortly.

**Comment by Nannoussa** [comment] 2020-08-07 08:23
@henon, Hello, I have a question if possible: I want to install a custom version of python and I can't use InstallDirectory cause it takes only the name of the file, not the path from where to take it.
Using EmbededPythonHome also doesn't seem to be right cause it just combines were to install with the directory name. And I don't seem to find where you're providing the full path to the python directory to be installed.
Could you please help me with this? Thanks a lot.

**Comment by henon** [comment] 2020-08-07 08:46
Is it a custom version of vanilla Python 3.7 or is it 3.8 or a completely different distribution like Anaconda?

**Comment by henon** [comment] 2020-08-07 09:53
In any case, I decided to split off the installation routines from Python.Included which embeds a specific Python distribution so that they can be used seperately. It will also allow to download the Python zip from the internet.

**Comment by Nannoussa** [comment] 2020-08-07 12:15
No, It's not a custom version it's the same one you have in the resources file but with a bit of adjustment.

**Comment by henon** [comment] 2020-08-07 12:43
OK, you can either embed that in a .NET assembly or put it on a web server for download. Either way, you can then use the new Installer I am splitting off to install it by using the EmbeddedResourceInstallationSource or the DownloadInstallationSource. Once I am done testing I'll push the new installer.

**Comment by henon** [comment] 2020-08-07 16:56
this is how embedding your own python distribution looks like. I'll also add this to the examples

```c#
using System;
using System.IO;
using System.Threading.Tasks;
using Python.Runtime;

namespace Python.Deployment.Example.EmbeddedResource
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // ================================================
            // This example demonstrates how to embed a Python distribution and install it locally 
            // ================================================

            // install in local directory. if you don't set it will install in local app data of your user account
            Python.Deployment.Installer.InstallPath = Path.GetFullPath(".");

            // see what the installer is doing
            Python.Deployment.Installer.LogMessage += Console.WriteLine;

            // ================================================
            // set the installation source to be the embedded python zip from our resources
            // ================================================
            Python.Deployment.Installer.Source = new Deployment.Installer.EmbeddedResourceInstallationSource()
            {
                Assembly = typeof(Program).Assembly,
                ResourceName = "python-3.8.5-embed-amd64.zip",
            };

            // install from the given source
            await Python.Deployment.Installer.SetupPython();

            // ok, now use pythonnet from that installation
            PythonEngine.Initialize();

            // call Python's sys.version to prove we are executing the right version
            dynamic sys=PythonEngine.ImportModule("sys");
            Console.WriteLine("### Python version:\n\t" + sys.version);

            // call os.getcwd() to prove we are executing the locally installed embedded python distribution
            dynamic os = PythonEngine.ImportModule("os");
            Console.WriteLine("### Current working directory:\n\t" + os.getcwd());
            Console.WriteLine("### PythonPath:\n\t" + PythonEngine.PythonPath);

        }
    }
}
```

**Comment by henon** [comment] 2020-08-07 17:11
All you need as a dependency is this: https://www.nuget.org/packages/Python.Deployment/1.0.0

**Comment by Nannoussa** [comment] 2020-08-13 08:19
I have issues using this EmbeddedResourceInstallationSource(), do I need to create a new class library and embed my resource in their or I can just embed the resource under a folder in my project and call it from there?
I used the second way, but it doesn't seem to work with typeof().Assembly. The assembly is my class where I am using the embedded resource right?
I searched the internet and found that most of the devs are using this kind of code:
`var fileName = "MyExamples.TestLibrary.mappings.xml";
var assembly = Assembly.GetExecutingAssembly();
var stream = assembly.GetManifestResourceStream(fileName);
 
if (stream == null)
{
    throw new FileNotFoundException("Cannot find mappings file.", fileName);
}
 
var doc = new XmlDocument();
doc.Load(stream);`
It didn't seem right to me to use a stream on a zip file. 
And if I use EmbeddedResourceInstallationSource() do I need to declare the Install Directory after it or not necessary? 
Thanks a lot @henon

**Comment by henon** [comment] 2020-08-13 08:29
you can use `var assembly = Assembly.GetExecutingAssembly();` to get the assembly. The zip file must be embedded resource of that executing assembly. If not, you can use any type that is defined exactly in the same assembly as you embedded the zip file in and use `typeof(MyType).Assembly` to get the assembly. 

 - Make sure the compile action of the zip file is "embedded resource"
- Also make sure the name you give to `EmbeddedResourceInstallationSource` is exactly the filename of the zip file. The folder it resides in is irrelevant.

Also, check out the new examples where I demonstrate that the `EmbeddedResourceInstallationSource` works.

**Comment by Nannoussa** [comment] 2020-08-18 09:35
Hello @henon , I wanted to test something on your project but when I cloned it I found a bunch of errors sharing the same issue: Python.Installer seems not to be recognized and it's weird indeed cause Installer is not under Python but under Python. Included or Python.Deployment !! So could you please tell me if there is something missing? Thank you. :)

**Comment by henon** [comment] 2020-08-18 09:39
You are right, I recompiled all and see the errors now.

**Comment by henon** [comment] 2020-08-18 09:53
Check it out, I just pushed. You might have to clean and rebuild

**Comment by Nannoussa** [comment] 2020-08-18 09:56
Yes it's good now Thanks ;)

**Comment by henon** [comment] 2020-09-04 18:49
@Nannoussa can this issue be closed? 

Btw: someone just improved the InstallWheel method significantly. It might be of interest to you.

**Closed** 2020-09-18 20:01 UTC
